### ISSUE TITLE
Chatbot will send two message in different chat bubbles,

### ISSUE THREAD

**Issue by volantebjb** [tdsoft/ChatBot-App_with-Android-and-Python#1]
Hi, cheers for sharing this on YouTube! Since I'm relatively new to Python and have zero knowledge of Kotlin, could you help me? I want the chatbot to send two chat bubbles at the same time but I can't get the right code for the Android app. 

This is my code for the ChatBotAPI.py:

    chatInput = request.form['chatInput']
    response = primary(chatInput)
    followup = secondary(chatInput)`

    if followup == "None" or None:
        return jsonify(chatBotReply=response)
    
    else:
        return jsonify({'chatBotReply':primary(chatInput),'chatBotReply2':secondary(chatInput)})

It seems to be working on Postman:

![image](https://user-images.githubusercontent.com/58124878/117463965-c7f0fa00-af82-11eb-98c5-8b9d28b5c003.png)

But I can't get it to work on the app. I haven't change anything yet in the original Kotlin files.

![image](https://user-images.githubusercontent.com/58124878/117464682-7dbc4880-af83-11eb-87ef-72fa811d13c4.png)

I hope you can help. Thank you!

**Comment by tdsoft** [comment]
Have you changed the ChatModel to match with the JSON reply you send from the API?

**Comment by volantebjb** [comment]
Not yet... It's still like this 

`data class ChatModel(val chat: String, val isBot: Boolean = false) {
}`

and the APIService

`interface APIService {
    @FormUrlEncoded
    @POST("chat")`
    `fun chatWithTheBit(@Field("chatInput") chatText : String ): Call<ChatResponse>
}`

`data class ChatResponse(val chatBotReply: String)`

Can you help me make this work? Thank you so much!

**Comment by tdsoft** [comment]
1. Change you the ChatResponse model as this Change you the ChatResponse model as this 
`data class ChatResponse(val chatBotReply: String, val chatBotReply2:String)` . 

2. Now you can receive the two chat replies to you Android app and now you have to change the "chatbotandroidapp/app/src/main/res/layout/listitem_chat.xml" file to show your two chats on the ListView as below.

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent"
    android:orientation="vertical"
    android:layout_height="wrap_content">

    <TextView
        android:padding="8dp"
        android:id="@+id/txtChat"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textSize="18sp"
        android:text="" />
		
     <TextView
        android:padding="8dp"
        android:id="@+id/txtChat2"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textSize="18sp"
        android:text="" />
</LinearLayout>
```

3. And then change the "inner class MyViewHolder" which is in "chatbotandroidapp/app/src/main/java/com/tdsoft/chatbotapp/AdapterChatBot.kt" as below

  ```
inner class MyViewHolder(parent: ViewGroup) : RecyclerView.ViewHolder(
        LayoutInflater.from(parent.context).inflate(R.layout.listitem_chat, parent, false)
    ) {
        fun bind(chat: ChatModel) = with(itemView) {
            if(!chat.isBot) {
                txtChat.setBackgroundColor(Color.WHITE)
                txtChat.setTextColor(Color.BLACK)
                txtChat.text = chat.chat
            }else{
                txtChat.setBackgroundColor(Color.CYAN)
                txtChat.setTextColor(Color.BLACK)
                txtChat.text = chat.chatBotReply
				
		txtChat2.setBackgroundColor(Color.CYAN)
                txtChat2.setTextColor(Color.BLACK)
                txtChat2.text = chat.chatBotReply2
            }
        }
    }
```

Now run the app and test.

**Comment by volantebjb** [comment]
Hey, thank you! I added everything you said and tested the app. It won't output anything so I also added some.

1. I edited the line in APIService.kt and changed it to:

`data class ChatResponse(val chatBotReply: String, val chatBotReply2: String)`

and the line in ChatModel.kt

`data class ChatModel(val chatBotReply: String, val chatBotReply2: String, val isBot: Boolean = false)`

2. In MainActivity.kt, class MainActivity, I edited the first line and added another `etChat.text.toString()`:

```
adapterChatBot.addChatToList(ChatModel(etChat.text.toString(), etChat.text.toString()))
            apiService.chatWithTheBit(etChat.text.toString()).enqueue(callBack)
            etChat.text.clear()
```

3. I also added `response.body()!!.chatBotReply2` in  line `adapterChatBot.addChatToList`: 

```
    private val callBack = object  : Callback<ChatResponse>{
        override fun onResponse(call: Call<ChatResponse>, response: Response<ChatResponse>) {
            if(response.isSuccessful &&  response.body()!= null){
                adapterChatBot.addChatToList(ChatModel(response.body()!!.chatBotReply,response.body()!!.chatBotReply2, true))
            }else{
                Toast.makeText(this@MainActivity, "Something went wrong", Toast.LENGTH_LONG).show()
            }
        }
```

I tested the app but the `chatInput` is being outputted too. 

![image](https://user-images.githubusercontent.com/58124878/117558967-ec98bf00-b0b3-11eb-9986-55b80026b163.png)

What do you think causes this? Cheers!

**Comment by tdsoft** [comment]
Oh I forgot to add changes to ChatModel.kt. I didn't do any running. So is this giving you the correct output now?

**Comment by tdsoft** [comment]
Do the below changes to Adapter inner class. We have to hide txtChat2 textbox when it is not the bot reply.
```
 inner class MyViewHolder(parent: ViewGroup) : RecyclerView.ViewHolder(
        LayoutInflater.from(parent.context).inflate(R.layout.listitem_chat, parent, false)
    ) {
        fun bind(chat: ChatModel) = with(itemView) {
            if(!chat.isBot) {
                txtChat.setBackgroundColor(Color.WHITE)
                txtChat.setTextColor(Color.BLACK)
                txtChat.text = chat.chat

                txtChat2.visibiility = View.GONE
            }else{
                txtChat2.visibiility = View.VISIBLE

                txtChat.setBackgroundColor(Color.CYAN)
                txtChat.setTextColor(Color.BLACK)
                txtChat.text = chat.chat

                txtChat2.setBackgroundColor(Color.CYAN)
                txtChat2.setTextColor(Color.BLACK)
                txtChat2.text = chat.chatBotReply2
            }
        }
    }
```

**Comment by volantebjb** [comment]
It worked now! Thank you so much for your time. Kudos!

![image](https://user-images.githubusercontent.com/58124878/117578098-41bdea80-b11f-11eb-9f74-0c0d7aaa4bfa.png)
